pub const MIGRATIONS: &str = "
CREATE TABLE IF NOT EXISTS `groups` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT, 
  `label` VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS `items` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`groupId`	INTEGER NOT NULL,
  `parentId` INTEGER,
  `label` VARCHAR(255) NOT NULL,
	FOREIGN KEY(`groupId`) REFERENCES `groups`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(`parentId`) REFERENCES `items`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `item_keys` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `itemId` INTEGER NOT NULL,
  `key` VARCHAR(255) NOT NULL,
	FOREIGN KEY(`itemId`) REFERENCES `items`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
);
";
